### ISSUE TITLE
Stale qemu-efi-aarch64 links

### ISSUE THREAD

**Issue by dscho** [jeremyd2019/winautoconfig#2]
The wiki links to https://packages.debian.org/experimental/qemu-efi-aarch64 (which is dead) and should instead point to https://packages.debian.org/sid/qemu-efi-aarch64.

**Comment by jeremyd2019** [comment]
Yeah, at the time I had used experimental, but then when I wrote up the wiki it was moved to sid.

**Comment by dscho** [comment]
Well, I opened this ticket to suggest to fix the links. The wiki is apparently set up in a way that disallows me from making those edits.

**Comment by jeremyd2019** [comment]
I added a link to `sid` as well.
